
service: uxs

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  stage: hack
  region: us-east-1

functions:
  getAccountById:
    handler: handler.getAccountById # get account by id - with no id return all accounts
    events:
      - http:
          method: GET
          path: accounts/{id}
          cors: true
  getAccounts:
    handler: handler.getAccountById # get account by id - with no id return all accounts
    events:
      - http:
          method: GET
          path: accounts/
          cors: true
  getProductById:
    handler: handler.getProductById # get account by id - with no id return all accounts
    events:
      - http:
          method: GET
          path: products/{id} # this won't allow pid as the path param, why?
          cors: true

  getProducts: # get all products
    handler: handler.getProducts # get products by id
    events:
      - http:
          method: GET
          path: products/


  rProductsForAccountId:
    handler: handler.rProductsForAccountId # get recommended product 
    events:
      - http:
          method: GET
          path: rproducts/{id}


  rProductsByProductId:
    handler: handler.rProductsByProductId # personalized by user
    events:
      - http:
          path: linkproducts/
          method: GET
          cors: true

  rAccountsForProduct:
    handler: handler.rAccountsForProduct # accounts for products
    events:
      - http:
          path: accountsforproducts/{pid}
          method: GET
          cors: true